# Generated by Django 4.2.21 on 2025-07-29 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_initial"),
        ("forum", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="forumcategory",
            name="school",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="forum_categories",
                to="accounts.school",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="forumcategory",
            name="description",
            field=models.TextField(blank=True, default=""),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="forumcategory",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="forumcategory",
            name="slug",
            field=models.SlugField(
                blank=True, help_text="Auto-generated from name", max_length=120
            ),
        ),
        migrations.AlterUniqueTogether(
            name="forumcategory",
            unique_together={("school", "slug")},
        ),
    ]
