# Generated by Django 4.2.21 on 2025-07-29 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forum", "0002_forumcategory_school_alter_forumcategory_description_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="forumcategory",
            options={"ordering": ["name"]},
        ),
        migrations.AlterField(
            model_name="forumcategory",
            name="slug",
            field=models.SlugField(blank=True, max_length=120),
        ),
    ]
