# Generated by Django 4.2.21 on 2025-08-05 10:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_studenttask"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("forum", "0003_alter_forumcategory_options_alter_forumcategory_slug"),
    ]

    operations = [
        migrations.CreateModel(
            name="PostAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="forum_attachments/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="PostLike",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "like_type",
                    models.CharField(
                        choices=[("LIKE", "Like"), ("UPVOTE", "Upvote")],
                        default="LIKE",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="forumthread",
            name="content",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="forumthread",
            name="school",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="forum_threads",
                to="accounts.school",
            ),
        ),
        migrations.AddField(
            model_name="forumthread",
            name="school_class",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="forum_threads",
                to="accounts.schoolclass",
            ),
        ),
        migrations.AlterField(
            model_name="forumpost",
            name="content",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="forumthread",
            name="category",
            field=models.CharField(
                choices=[
                    ("GENERAL", "General Discussion"),
                    ("CLASS", "Class Discussion"),
                    ("MANAGEMENT", "School Management"),
                ],
                default="GENERAL",
                max_length=20,
            ),
        ),
        migrations.DeleteModel(
            name="ForumCategory",
        ),
        migrations.AddField(
            model_name="postlike",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="likes",
                to="forum.forumpost",
            ),
        ),
        migrations.AddField(
            model_name="postlike",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="post_likes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="postattachment",
            name="post",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attachments",
                to="forum.forumpost",
            ),
        ),
        migrations.AddField(
            model_name="postattachment",
            name="thread",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attachments",
                to="forum.forumthread",
            ),
        ),
        migrations.AddField(
            model_name="postattachment",
            name="uploader",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterUniqueTogether(
            name="postlike",
            unique_together={("post", "user", "like_type")},
        ),
    ]
