# Generated by Django 4.2.21 on 2025-08-05 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("forum", "0004_postattachment_postlike_forumthread_content_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="forumthread",
            name="content",
        ),
    ]
