# Generated by Django 4.2.21 on 2025-08-05 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forum", "0005_remove_forumthread_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="forumthread",
            name="content",
            field=models.TextField(default=""),
        ),
    ]
