# Generated by Django 4.2.21 on 2025-08-05 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("forum", "0006_forumthread_content"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="forumthread",
            name="content",
        ),
    ]
