# Generated by Django 4.2.21 on 2025-08-06 14:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("accounts", "0003_studenttask"),
        ("forum", "0009_alter_forumpost_author_alter_forumpost_content_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="postattachment",
            name="thread",
        ),
        migrations.AlterField(
            model_name="forumpost",
            name="author",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="forum_posts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="forumpost",
            name="content",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="forumthread",
            name="author",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="forum_threads",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="forumthread",
            name="school",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="forum_threads",
                to="accounts.school",
            ),
        ),
    ]
