# Generated by Django 4.2.21 on 2025-08-06 14:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("accounts", "0003_studenttask"),
        ("forum", "0010_remove_postattachment_thread_alter_forumpost_author_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="postattachment",
            name="thread",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attachments",
                to="forum.forumthread",
            ),
        ),
        migrations.AlterField(
            model_name="forumpost",
            name="author",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="forum_posts",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="forumpost",
            name="content",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="forumthread",
            name="author",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="forum_threads",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="forumthread",
            name="school",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="forum_threads",
                to="accounts.school",
            ),
        ),
    ]
