# Generated by Django 4.2.21 on 2025-08-07 06:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_studenttask"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("forum", "0011_postattachment_thread_alter_forumpost_author_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="postattachment",
            name="thread",
        ),
        migrations.AlterField(
            model_name="forumpost",
            name="author",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="forum_posts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="forumthread",
            name="author",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="forum_threads",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="forumthread",
            name="school",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="forum_threads",
                to="accounts.school",
            ),
        ),
        migrations.AlterField(
            model_name="postattachment",
            name="post",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attachments",
                to="forum.forumpost",
            ),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="ForumCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                ("slug", models.SlugField()),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="forum_categories",
                        to="accounts.school",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Forum Categories",
                "ordering": ["name"],
                "unique_together": {("school", "slug")},
            },
        ),
        migrations.AlterField(
            model_name="forumthread",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="threads",
                to="forum.forumcategory",
            ),
        ),
    ]
