# Generated by Django 4.2.21 on 2025-08-07 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_studenttask"),
    ]

    operations = [
        migrations.AddField(
            model_name="userdailyactivity",
            name="library_study_duration_minutes",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Total study duration from the general library timer for this day in minutes.",
            ),
        ),
    ]
