# Generated by Django 4.2.21 on 2025-08-11 07:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_userdailyactivity_library_study_duration_minutes"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="studenttask",
            options={"ordering": ["due_date", "completed"]},
        ),
        migrations.AlterField(
            model_name="customuser",
            name="verification_token",
                        field=models.UUIDField(editable=False, unique=True, null=True),
        ),
        migrations.AlterField(
            model_name="recentactivity",
            name="activity_type",
            field=models.CharField(
                choices=[
                    ("Lesson", "Lesson"),
                    ("Quiz", "Quiz"),
                    ("Reward", "Reward"),
                    ("Login", "Login"),
                    ("Logout", "Logout"),
                    ("Library", "Library"),
                    ("Forum", "Forum"),
                ],
                max_length=50,
            ),
        ),
    ]
