# Generated by Django 4.2.21 on 2025-08-11 08:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_alter_studenttask_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="studenttask",
            options={"ordering": ["due_date", "created_at"]},
        ),
        migrations.AlterField(
            model_name="customuser",
            name="verification_token",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, null=True, unique=True
            ),
        ),
    ]
