# Generated by Django 4.2.21 on 2025-07-25 10:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("content", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reward",
            name="criteria_type",
            field=models.CharField(
                choices=[
                    ("WEEK_WARRIOR", "Week Warrior"),
                    ("CONSISTENCY_CHAMPION", "Consistency Champion"),
                    ("MASTER_OF_CONSISTENCY", "Master of Consistency"),
                    ("PERFECT_ATTENDANCE_STAR", "Perfect Attendance Star"),
                    ("QUIZ_MASTER", "Quiz Master"),
                    ("COMPLETION_CROWN", "Completion Crown"),
                    ("PIONEER_GRADUATE", "Pioneer Graduate"),
                ],
                max_length=50,
                unique=True,
            ),
        ),
        migrations.CreateModel(
            name="StudentResource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "resource_type",
                    models.CharField(
                        choices=[
                            ("BOOK", "Book (PDF/ePub)"),
                            ("NOTE", "Personal Note"),
                            ("VIDEO", "Video Link"),
                        ],
                        max_length=10,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        help_text="For uploaded books or notes.",
                        null=True,
                        upload_to="student_resources/",
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        blank=True, help_text="For video links.", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_resources",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
    ]
