# Generated by Django 4.2.21 on 2025-07-28 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0002_alter_reward_criteria_type_studentresource"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentresource",
            name="content",
            field=models.TextField(
                blank=True, help_text="For text-based notes.", null=True
            ),
        ),
        migrations.AlterField(
            model_name="studentresource",
            name="file",
            field=models.FileField(
                blank=True,
                help_text="For uploaded books or PDFs.",
                null=True,
                upload_to="student_resources/",
            ),
        ),
    ]
