# Generated by Django 4.2.21 on 2025-08-11 07:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_alter_studenttask_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("content", "0003_studentresource_content_alter_studentresource_file"),
    ]

    operations = [
        migrations.CreateModel(
            name="ManualReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject_name", models.CharField(max_length=100)),
                ("test_name", models.CharField(max_length=255)),
                (
                    "test_type",
                    models.CharField(
                        choices=[
                            ("SLIP_TEST", "Slip Test"),
                            ("UNIT_TEST", "Unit Test"),
                            ("QUARTERLY", "Quarterly"),
                            ("ANNUAL", "Annual"),
                        ],
                        max_length=20,
                    ),
                ),
                ("score", models.FloatField()),
                ("max_score", models.FloatField(default=100.0)),
                ("grade", models.CharField(blank=True, max_length=5)),
                ("remarks", models.TextField(blank=True)),
                ("report_date", models.DateField()),
                (
                    "created_by",
                    models.ForeignKey(
                        limit_choices_to={"role__in": ["Teacher", "Admin"]},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="manual_reports",
                        to="accounts.school",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="manual_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-report_date"],
            },
        ),
    ]
