# Generated by Django 4.2.21 on 2025-08-12 11:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("content", "0004_manualreport"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_lessons",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
