# Generated by Django 4.2.21 on 2025-08-27 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0005_lesson_created_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="manualreport",
            name="ai_analysis",
            field=models.JSONField(
                blank=True,
                help_text="Stores the structured AI-generated report analysis.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="manualreport",
            name="remarks",
            field=models.TextField(
                blank=True, help_text="Teacher's manual remarks for a specific subject."
            ),
        ),
    ]
