# Generated by Django 4.2.21 on 2025-08-27 14:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("content", "0006_manualreport_ai_analysis_alter_manualreport_remarks"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="manualreport",
            options={"ordering": ["-report_date", "test_name"]},
        ),
        migrations.RenameField(
            model_name="manualreport",
            old_name="grade",
            new_name="overall_grade",
        ),
        migrations.AddField(
            model_name="manualreport",
            name="scores_data",
            field=models.JSONField(
                default="",
                help_text="Stores an array of subject performances, e.g., [{'subject_name': 'Math', 'score': 85, 'max_score': 100, 'remarks': 'Good'}]",
            ),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="manualreport",
            unique_together={("student", "test_name", "report_date")},
        ),
        migrations.RemoveField(
            model_name="manualreport",
            name="max_score",
        ),
        migrations.RemoveField(
            model_name="manualreport",
            name="remarks",
        ),
        migrations.RemoveField(
            model_name="manualreport",
            name="score",
        ),
        migrations.RemoveField(
            model_name="manualreport",
            name="subject_name",
        ),
    ]
