# Generated by Django 4.2.21 on 2025-08-12 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0002_alter_event_target_class_studenttask"),
    ]

    operations = [
        migrations.DeleteModel(
            name="StudentTask",
        ),
    ]
